import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { cookies } from "next/headers";
// Make sure you import whatever token verification function you use in lib/auth
import { verifyToken } from "@/lib/auth"; 

// Helper function to authenticate the request
async function getAuthenticatedAcademy() {
  const cookieStore = await cookies();
  const token = cookieStore.get("auth_token")?.value;
  
  if (!token) return null;

  try {
    const decoded = await verifyToken(token);
    // Ensure only academies can access these routes
    if (decoded.role !== "academy") return null;
    return decoded;
  } catch (error) {
    return null;
  }
}

// GET: Fetch all players belonging to the logged-in Academy
export async function GET(req: Request) {
  try {
    const academyUser = await getAuthenticatedAcademy();
    if (!academyUser) {
      return NextResponse.json({ error: "Unauthorized access" }, { status: 401 });
    }

    const players = await prisma.player.findMany({
      where: { 
        academyId: academyUser.userId 
      },
      orderBy: { 
        createdAt: "desc" 
      },
      include: {
        videos: true, // Includes the videos so the academy can see how many each player has
      }
    });

    return NextResponse.json({ players });
  } catch (error) {
    console.error("Error fetching players:", error);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}

// POST: Add a new player to the Academy's roster
export async function POST(req: Request) {
  try {
    const academyUser = await getAuthenticatedAcademy();
    if (!academyUser) {
      return NextResponse.json({ error: "Unauthorized access" }, { status: 401 });
    }

    const body = await req.json();
    const { name, age, position, nationality, height, weight, preferredFoot } = body;

    // Real name is the only strictly required field to create the shell profile
    if (!name) {
      return NextResponse.json({ error: "Player name is required" }, { status: 400 });
    }

    const newPlayer = await prisma.player.create({
      data: {
        name,
        age: age ? parseInt(age) : null,
        position,
        nationality,
        height,
        weight,
        preferredFoot,
        academyId: academyUser.userId,
        // uniqueId is automatically generated by the database
      },
    });

    return NextResponse.json({ player: newPlayer }, { status: 201 });
  } catch (error) {
    console.error("Error creating player:", error);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
